### ISSUE TITLE
[Business Approvals Kit - BUG] Custom connector error

### ISSUE THREAD

**Issue by KGMunaweera** [microsoft/powercat-business-approvals-kit#135]
### Describe the issue

When I try to test the connector, I receive this error massage {
  "error": {
    "code": "0x80072560",
    "message": "The user is not a member of the organization."
  }
}

### What solution version are you using?

BusinessApprovalKit_1.0.20231117.1_managed.zip

### What app or flow are you having the issue with?

Approvals Kit custom connector

AB#1746

**Comment by Ramakrishnan24689** [comment]
Please make sure you have modified the host URL in the `General tab` and Resource URL in `Security Tab` of the custom connector based on your target environment details as mentioned in the Novemeber 2023 release note - Setup Guide section.

We will remove the environment variable and provide more information around this process in subsequent releases to make the installation easier.

<img width="578" alt="image" src="https://github.com/microsoft/powercat-business-approvals-kit/assets/11135056/2ed5695f-12be-47d8-88f5-f2eec33e7da4">

**Comment by KGMunaweera** [comment]
Thanks - populating the host value under general section seems to have fixed the issue.

**Comment by Grant-Archibald-MS** [comment]
Updated the release notes to reference this issue

**Comment by true2blue** [comment]
Hi Dude, 
I got the same issue even I had set the host value in `general` tab and `security` tab as value from `Approval Kit Org Url`, but still got the error "The user is not a member of the organization", any idea what is going wrong ? Thanks.
![1](https://github.com/user-attachments/assets/7b385bd5-27a5-4ec7-b7be-40cb0c440039)
![2](https://github.com/user-attachments/assets/e6392f09-6a2c-4212-aa44-d2e3659b33d0)
![3](https://github.com/user-attachments/assets/0761a4fe-3dbc-45bd-ae4a-ce94412e19d3)
![4](https://github.com/user-attachments/assets/0da6804a-726a-4283-83ff-ce8591ceae42)
