### ISSUE TITLE
[Business Approvals Kit - BUG] Cannot search for or find approver on Create Node when creating a stage.

### ISSUE THREAD

**Issue by russrimm** [microsoft/powercat-business-approvals-kit#143]
### Describe the issue

When creating a node within the process designer, trying to add an approver.  The approver dropdown/combobox doesn't have search enabled and if scrolling through the available users, it does not show all users.

### Expected Behavior

Able to search for users vs being able to choose from only the top:n from AAD

### What solution version are you using?

1.0.20231117.1_unmanaged

### What app or flow are you having the issue with?

BAManagement

AB#1761

**Comment by Grant-Archibald-MS** [comment]
@russrimm while this bug is being looked at one alternative option to consider would be to create a variable for the approval workflow and use that value as the approver

**Comment by Ramakrishnan24689** [comment]
@russrimm - Thanks for helping us with Approvals Kit. This issue is addressed in Dec2023 Year-end release version -**BusinessApprovalKit_1.0.20231222.1**.
