### ISSUE TITLE
[Business Approvals Kit - BUG] Two active version of process template visible

### ISSUE THREAD

**Issue by Ramakrishnan24689** [microsoft/powercat-business-approvals-kit#150]
### Describe the issue

Able to see two active versions after publishing the process.

### Expected Behavior

There should be only one active version shown of process template

### What solution version are you using?

BusinessApprovalKit_1.0.20231214.1_managed.zip

### What app or flow are you having the issue with?

Business Approval Management App - Process Designer Custom Page

### Steps To Reproduce

1. Create a Business Approval Process.
2. Save and Publish.
3. Make small change and try saving and publishing again.

### Anything else?

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/11135056/d9c162e5-ab7a-4e71-8db2-7ca0df3873e7)

AB#1796

**Comment by shrikant-singh31** [comment]
Closing as the issue was fixed with the Jan-24 release
