### ISSUE TITLE
[Business Approvals Kit - BUG] Error loading control

### ISSUE THREAD

**Issue by KGMunaweera** [microsoft/powercat-business-approvals-kit#152]
### Describe the issue

![business approval kit bug 1](https://github.com/microsoft/powercat-business-approvals-kit/assets/153534804/98eb04b8-3b88-4573-8bb1-0d7613674aaa)

Error loading control on Received Approval Reqest section in the home page. 

### What solution version are you using?

BusinessApprovalKit_1.0.20231213.2_managed

### What app or flow are you having the issue with?

-

### Steps To Reproduce

-

AB#1802

**Comment by Grant-Archibald-MS** [comment]
Included with February 2024 release https://github.com/microsoft/powercat-business-approvals-kit/releases/tag/BusinessApprovalKit-February2024
