### ISSUE TITLE
[Business Approvals Kit - BUG] Schema Validation Issue

### ISSUE THREAD

**Issue by WorkWithMeHere** [microsoft/powercat-business-approvals-kit#155]
### Describe the issue

When testing the custom connector, a an error is shown on the GetApprovalDataFields:

Property "" type mismatch, Expected: "object", Actual: "string".

This is shown for all operations and are returning a 401 error

### Expected Behavior

Per the Learn steps (https://learn.microsoft.com/en-us/power-automate/guidance/business-approvals-templates/setup) the operations should run successfully with a status of 200

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Custom connectors

### Steps To Reproduce

Under the Security tab, modify the following:

Select Authentication type as OAuth 2.0.
Enter the Client ID, Secret noted in previous section.
Specify the environment URL under Resource URL section.
Copy the Redirect URL

Open the created Entra App Registration

Select Authentication

In the Web Redirect URIs add the Redirect URL

Select Save to update the App Registration

Switch back to the custom connector.

Select Update connector.

Under the Test tab, create a New connection.

Specify the account details for the connection and allow access if prompted.
Edit the Custom connector again and test the GetPublishedWorkflow operation.

The operation should run successfully with status as 200.

AB#1820

**Comment by Ramakrishnan24689** [comment]
@WorkWithMeHere - Can you please confirm if

a) You have modified the host URL in the General tab and Resource URL in Security Tab of the custom connector based on your target environment details as mentioned in the release note - Setup Guide section and updated the connector.
b) You are able to create the connection for the custom connector inside PowerAutomate.

<img width="689" alt="image" src="https://github.com/microsoft/powercat-business-approvals-kit/assets/11135056/a8619a26-5138-4ed1-a3a4-ae8fb6849923">

**Comment by WorkWithMeHere** [comment]
Thanks - changing the host URL in the general channel fixed the issue and we are now able to use the approvals kit.

Thank you 👍

**Comment by WorkWithMeHere** [comment]
For anyone else who happens across this page - update the general tab with the environment URL (which can be found in the power platform admin settings). Should be in the format of the image below
<img width="400" alt="GeneralTab" src="https://github.com/microsoft/powercat-business-approvals-kit/assets/148922064/2c18f27d-bc17-484b-af9d-a5ac970320d7">
