### ISSUE TITLE
[Business Approvals Kit - Feature]: Search for approver

### ISSUE THREAD

**Issue by WorkWithMeHere** [microsoft/powercat-business-approvals-kit#158]
### Is your feature request related to a problem? Please describe.

Nope, not related to a problem at all.

### Describe the solution you'd like

In the approvals centre, when an approver is selected there is no option to type ahead or search for a user to complete the approvals. Instead you must scroll to find the approver.

It would be great to be able to search for an approver instead of scrolling through.

AB#1833

**Comment by Grant-Archibald-MS** [comment]
Related to #143

**Comment by Ramakrishnan24689** [comment]
@WorkWithMeHere  - Thanks for helping us with Approvals Kit. This issue is addressed in Dec2023 Year-end release version -**BusinessApprovalKit_1.0.20231222.1**.
