### ISSUE TITLE
[Business Approvals Kit - BUG] New Work flow is not Creating

### ISSUE THREAD

**Issue by ArunVRPowerDoc365** [microsoft/powercat-business-approvals-kit#166]
### Describe the issue

I Created the New Flow, Click Save and Published. But my submitted Workflow is Not showing.
![Screenshot 2023-12-21 114047](https://github.com/microsoft/powercat-business-approvals-kit/assets/154434524/20c457ad-2153-4999-a26e-47b30b99db20)

The Flow are failed to create the Workflow 
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/154434524/7f682e3d-f10b-4f12-bfed-e01a0ef2c3ce)
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/154434524/e8070993-c49a-4e7e-ad93-9341c3e60f0c)

So the Workflow is not created and not showing in the Power Automate
![Screenshot 2023-12-21 112431](https://github.com/microsoft/powercat-business-approvals-kit/assets/154434524/38a789c3-0a25-4446-9600-ad7b0b9417d7)

### What solution version are you using?

1.0.20231214.1

### What app or flow are you having the issue with?

BACore | Publish Process

AB#1889

**Comment by miguelverweij** [comment]
This has to do with the name being empty. With the year end update this should be resolved. The naming isn't perfect yet though. I have described a quick fix in issue #156. I hope this works for you

**Comment by shrikant-singh31** [comment]
Closing the issue as it is fixed now with the latest Feb-24 release for https://github.com/microsoft/powercat-business-approvals-kit/issues/156
