### ISSUE TITLE
[Business Approvals Kit - Feature]: Microsoft Graph User Out Of Office Settings and Working Hours

### ISSUE THREAD

**Issue by miguelverweij** [microsoft/powercat-business-approvals-kit#169]
### Is your feature request related to a problem? Please describe.

The current solution forces approvers to set their out of office in the Approvals Kit application. The majority of users will set up an auto-reply in Outlook when they will leave the office, and might not think about setting it up in this application. The whole idea of this delegation of approval is then not activated, which makes this solution as a whole less interesting. The same counts for working hours, although that might have less direct impact. 

### Describe the solution you'd like

There is already an app registration required. Although in beta, it would be nice if the delegation process can use the https://graph.microsoft.com/beta/users/{user-id}/presence and https://graph.microsoft.com/v1.0/users/{user-id}/mailboxSettings call to check if the user is oof and working hours, and act accordingly.
Setting up the delegated and backup delegated could still be done in the Approvals kit application, but these two are already managed elsewhere.

AB#1896

**Comment by Grant-Archibald-MS** [comment]
Consider adding environment variable that enables this feature. If the feature is enabled make call for mailbox settings, if feature not enables use the existing Out of office setting

**Comment by Grant-Archibald-MS** [comment]
Also consider https://learn.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=http calendar getSchedule to determine working days
