### ISSUE TITLE
[Business Approvals Kit - BUG] Cannot create Flow

### ISSUE THREAD

**Issue by ahmadpirani** [microsoft/powercat-business-approvals-kit#171]
### Describe the issue

Upon using the Approvals connector, I get below error message.
"The response from API 'cat-5fapprovals-20kit-5f2c9665d8a993eb93' operation 'GetApprovalDataFields' with status code '200' does not contain a valid OpenAPI schema object."

The custom connector does test out correctly without any errors. The error occurs while using it. The solution to such similar error is provided here.
https://powerusers.microsoft.com/t5/Using-Connectors/Dynamic-Schema-in-Custom-Connector-doesn-t-work-suddenly/td-p/655633

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/11561396/b61fcaf4-d921-421d-955d-230c3fb6c13a)

### Expected Behavior

Should be able to use the custom connector.

### What solution version are you using?

Whichever is the latest

### What app or flow are you having the issue with?

Custom Connector

### Steps To Reproduce

Create a flow
Use the custom connector.
Select a published Approval workflow

AB#1912

**Comment by shrikant-singh31** [comment]
Hi @ahmadpirani, We tried reproducing the bug at our end but we cannot. We are able to select the process and use the custom connector.
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/149066866/92832cd9-699f-4218-8eff-fa5c4e2603c3)
We request you to try reimporting and setting up the solution. We are keeping this issue opened. Please update here if you still face the same issue.

**Comment by ahmadpirani** [comment]
Shrikant,

I uninstalled the managed solution completed with all the references of the custom connector, and then imported the solution again. That resolved the issue.

Thanks for your response.

**Comment by Grant-Archibald-MS** [comment]
Closing the issue as resolved
