### ISSUE TITLE
[Business Approvals Kit - BUG] Webresource does not exist

### ISSUE THREAD

**Issue by ahmadpirani** [microsoft/powercat-business-approvals-kit#172]
### Describe the issue

cat_businessapproval_designerinstructions  There is no web resource with this name,

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/11561396/bfa8e949-f6ff-4994-a7b6-1e32956d2f0a)

### Expected Behavior

Web resource must be present in the solution.

### What solution version are you using?

Whichever is the latest

### What app or flow are you having the issue with?

None

AB#1913

**Comment by shrikant-singh31** [comment]
Closing as the issue was fixed with the Jan-24 release
