### ISSUE TITLE
[Business Approvals Kit - BUG] Stage loses/changes values

### ISSUE THREAD

**Issue by ahmadpirani** [microsoft/powercat-business-approvals-kit#174]
### Describe the issue

The stage with If/Else condition keeps changes its value if you go to edit after a save. It also shows incorrect condition in the designer.

**Create:**
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/11561396/aa59e006-feaf-4214-9ea0-b3813e5de2db)

**Designer:**
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/11561396/29faec3c-68cf-4c68-830d-da2a2c719bdc)

**Up on edit:**
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/11561396/b07fe531-013f-4b99-bae0-493fdec24194)

### Expected Behavior

Create page, designer, and edit should retain correct values. Right now it is not sure what the system is saving in the backend since all three values are different. 

### What solution version are you using?

Whichever is the latest

### What app or flow are you having the issue with?

None`

### Steps To Reproduce

Add two variables to Process Designer
First a text variable Name, and only then a second variable Price as number
Create a stage with If/Else condition
Select Price and select Greater than equal to
Add static value 400
Save
Check that designer shows Price equal to instead of greater than or equal to
Click Edit stage
Edit condition
Notice that instead of Price, Name variable is selected and operand is Equals

AB#1915

**Comment by Grant-Archibald-MS** [comment]
Included with February 2024 release https://github.com/microsoft/powercat-business-approvals-kit/releases/tag/BusinessApprovalKit-February2024
