### ISSUE TITLE
[Business Approvals Kit - BUG] Associate flows with apps for Power Automate licensing

### ISSUE THREAD

**Issue by martintoelk** [microsoft/powercat-business-approvals-kit#182]
### Describe the issue

I realized that none of the flows from the Approval Kit are associated with any of the apps. With the new licensing model for Power Automate, this is getting interesting.

Do you plan on associating the flows in one of the next releases or is that something that I should do myself? Or did you do that already and I simply need to upgrade?

As as reference, please use this CoE Ticket
https://github.com/microsoft/coe-starter-kit/issues/6713

CoE show the following Cloud Flows at risk of suspension
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/24940711/ec5c26ad-0cb3-470f-8188-7c4cb10803b5)

### Expected Behavior

Cloud Flows are Associated with the Apps

### What solution version are you using?

1.0.20231222.1

### What app or flow are you having the issue with?

Cloud Flows

### Steps To Reproduce

1. Create a new Environemnt
2. Setup Approval Kit as described
3. Wait several Days
4. CoE / Cloud Flow at risk powershell will mark the follwong Cloud Flows

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/24940711/57699592-b97a-4304-b65f-81ee273ff084)

AB#1965

**Comment by Grant-Archibald-MS** [comment]
@martintoelk The Power Automate cloud flows of the Approvals Kit will require a Premium Power Automate license as they use Dataverse and Custom connectors

**Comment by martintoelk** [comment]
Thanks! After thinking more globally about the license requirement, it starts to make sense.
