### ISSUE TITLE
[Business Approvals Kit - QUESTION] Failed Import of solution file in newly created dev environment

### ISSUE THREAD

**Issue by TG788** [microsoft/powercat-business-approvals-kit#184]
### What is your question?

> 
![Capture](https://github.com/microsoft/powercat-business-approvals-kit/assets/21050181/8160c26a-a45d-41c9-8fa3-6f72a024c383)

I receive a network error message when importing the Contoso Coffee solution file into my newly created development environment in PowerApps. I've also tried importing the solution into existing dev environments and all attempts are unsuccessful.

I used the below link to download the Contoso Coffee solution file
https://learn.microsoft.com/en-us/training/modules/approvals-kit-workshop/import-contoso-coffee

Is there any other site or place for me to download this solution file from?

### What solution version are you using?

AppinaDay Trainer Package zip file

### What app or flow are you having the issue with?

Contoso Coffee solution

AB#1980

**Comment by Grant-Archibald-MS** [comment]
@TG788  When download the [AppinaDay Trainer Package.zip](https://aka.ms/appinadayTrainer/) ensure the following

1. Unzip AppinaDay Trainer Package.zip
2. Open the "Completed Lab Solution for students" folder
3. Open the "Module 2" folder
4. Import solution from the **ContosoCoffee_1_0_0_2.zip** file from the Module 2

**Comment by Grant-Archibald-MS** [comment]
Closing the issue as the required file is ContosoCoffee_1_0_0_2.zip that is inside the [AppinaDay Trainer Package.zip](https://aka.ms/appinadayTrainer/) file
