### ISSUE TITLE
[Business Approvals Kit - BUG] Able to add text as default value in a variable of data type Number 

### ISSUE THREAD

**Issue by shrikant-singh31** [microsoft/powercat-business-approvals-kit#194]
### Describe the issue

While creating a variable of type Number, user can enter a a text default value.

### Expected Behavior

User should not be able to only numeric value

### What solution version are you using?

1.0.20240110.1

### What app or flow are you having the issue with?

Business Approval Management

### Steps To Reproduce

1. Click on variables.
2. Try creating variable of type Number.
3. Enter text in default value

### Anything else?

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/149066866/d87607b2-afb2-4aaa-988a-fa2eb93144cd)

AB#2154

**Comment by Grant-Archibald-MS** [comment]
Included with February 2024 release https://github.com/microsoft/powercat-business-approvals-kit/releases/tag/BusinessApprovalKit-February2024
