### ISSUE TITLE
[Business Approvals Kit - BUG] Able to enter text for condition target request data in Stage

### ISSUE THREAD

**Issue by shrikant-singh31** [microsoft/powercat-business-approvals-kit#195]
### Describe the issue

1. Create a variable of type number.
2. Create a stage with a If-Else/Switch condition.
3. Select Request Data in Source.
4. Select the numeric variable in Request Data control.
5. Under Static Value try entering characters for target.

### Expected Behavior

It should allow only numeric character for Request Data of type number.

### What solution version are you using?

1.0.20240110.1

### What app or flow are you having the issue with?

Business Approval Management

### Steps To Reproduce

1. Create a variable of type number.
2. Create a stage with a If-Else/Switch condition.
3. Select Request Data in Source.
4. Select the numeric variable in Request Data control.
5. Under Static Value try entering characters for target.

### Anything else?

<img width="954" alt="image" src="https://github.com/microsoft/powercat-business-approvals-kit/assets/149066866/61f22f65-4854-45b4-8273-e14a4615a8a0">

AB#2155

**Comment by Grant-Archibald-MS** [comment]
Included with February 2024 release https://github.com/microsoft/powercat-business-approvals-kit/releases/tag/BusinessApprovalKit-February2024
