### ISSUE TITLE
[Business Approvals Kit - Feature]: Add new parameter "External Reference" in custom connector

### ISSUE THREAD

**Issue by shrikant-singh31** [microsoft/powercat-business-approvals-kit#197]
### Is your feature request related to a problem? Please describe.

Currently we cannot update the approval outcome to the source as we do not have any provision to store reference of the external source.

### Describe the solution you'd like

This change will require the following updates:
1.Add a new optional parameter to the custom connector.
2.Add a new External Identifier column to the Business Approval Workflow table.
3. Update flow to store reference in above table.

AB#2178

**Comment by Grant-Archibald-MS** [comment]
Included in February 2024 Release https://github.com/microsoft/powercat-business-approvals-kit/releases/tag/BusinessApprovalKit-February2024
