### ISSUE TITLE
[Business Approvals Kit - BUG] Custom Responses Not Working

### ISSUE THREAD

**Issue by MCSDWes** [microsoft/powercat-business-approvals-kit#242]
### Describe the issue

Creating an approval with custom responses is not working correctly.  When using custom responses the format that is noted does not create two separate buttons.  I tried several different formats but none worked correctly.

**Node Instructions**
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/68615610/c2d2130d-f750-450b-a737-df517c4e42cd)

**Node**
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/68615610/839393c2-40fa-480b-a753-babfcfb6f5af)

**Teams Approval Only shows one button**
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/68615610/7e1aab5f-dcea-466d-98f2-8fbf53a9177e)

**Email Approval shows no buttons just a submit**
![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/68615610/05ebf7d9-c29f-474b-838a-1f527e543fb5)

### Expected Behavior

Approval to show custom responses via Teams and Email.

### What solution version are you using?

1.0.20240305.1 = March Release

### What app or flow are you having the issue with?

Node - custom responses

### Steps To Reproduce

See the screenshots above.

### Anything else?

NA

AB#2676

**Comment by Grant-Archibald-MS** [comment]
This issue is due to setting the custom responses using a dynamic list if option in the cloud flow. Further investigation is needed with core engineering to resolve this issue

**Comment by MCSDWes** [comment]
Verified this is now working and can be marked as Completed.
