### ISSUE TITLE
[Business Approvals Kit - BUG] After save stage with conditional the TRUE / FALSE nodes are not displayed

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-business-approvals-kit#45]
### Describe the issue

Not showing the + button when adding a stage

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/31553604/2fc4e66f-10f4-4299-8bf6-48a5058bf5a3)

After saving the Workflow and reopen the Process Designer the conditional node items for TRUE and FALSE are visible as expected

### Expected Behavior

That the TRUE / FALSE options of a If / Else is displayed after the add stage dialog is closed.

AB#736

**Comment by Ramakrishnan24689** [comment]
@shrikant-singh31, Even though we have modern designer as an alternate option, we would like to fix the existing branch(nested gallery)) which doesn't show up after adding new conditional stages in canvas component version.

**Comment by Ramakrishnan24689** [comment]
Closing this issue as fixed with the release of **BusinessApprovalKit_1.0.20231222.1**.
