### ISSUE TITLE
[Business Approvals Kit - BUG] Publish Workflow

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-business-approvals-kit#50]
### Describe the issue

user needs to wait for the workflow to be published. You can use the Refresh to update the publish status to update published

.

### Expected Behavior

Suggestion to consider: 
1. Add a label "This process will take up to 1 minute to complete."
2. Add a timer that automatically refresh status

### What solution version are you using?

1.0.20231107.1

AB#741

**Comment by shrikant-singh31** [comment]
Closing the issue as it was fixed with the Jan-24 release
