### ISSUE TITLE
[Business Approvals Kit - BUG] My Settings Underline

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/powercat-business-approvals-kit#52]
### Describe the issue

This information text on the My Settings screen looks like it is a hyperlink. 

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/31553604/547d21ae-1077-4cac-866e-8c58f1a4edb3)

### Expected Behavior

 Perhaps remove the underline.

AB#743

**Comment by shrikant-singh31** [comment]
Closing the issue as it was fixed with the Jan-24 release
