### ISSUE TITLE
[Business Approvals Kit - BUG] Disallow First & Second stage to swap

### ISSUE THREAD

**Issue by Ramakrishnan24689** [microsoft/powercat-business-approvals-kit#90]
### Describe the issue

The First Stage in Process Designer should not be allowed to Move down, neither the Second stage should be allowed to move up.

This is due to the current limitation of not allowing conditions in the first stage.

<img width="934" alt="image" src="https://github.com/microsoft/powercat-business-approvals-kit/assets/11135056/f71ad399-6ae5-498a-acf5-0a0f540650c8">

### Expected Behavior

Even though it is handled during Publishing phase of a Process(Workflow), it will be good to disable the option for first and second stages to move down and up respectively.

### What app or flow are you having the issue with?

Business Approval Management - app

AB#901

**Comment by Grant-Archibald-MS** [comment]
Included with February 2024 release https://github.com/microsoft/powercat-business-approvals-kit/releases/tag/BusinessApprovalKit-February2024
